import React from 'react'
import BottomDrawer from '../Common/BottomDrawer/index.js'
import TabbedComponent from '../Common/TabbedComponent/index.js'
import LiveTvChannelPage from '../LiveTv/ChannelPage/index.js'
import ChannelBanner from '../LiveTv/ChannelPage/index.js'
import LiveTvPlayer from '../LiveTv/Player/index.js'
import LiveTvHome from '../LiveTv/HomePage'
import RadioHome from '../Radio/HomePage/index.js'
import RadioPlayer from '../Radio/Player/index.js'
import WishlistHome from '../Wishlist/HomePage/index.js'
import SeeAllPlaylistContentHomePage from '../SeeAll/HomePage/index.js'
import ImageSlider from '../Common/Carousal_Banner/index.js'
import VerticalHorizontalList from '../VirtualGrid/index.js'
import HorizontalList from '../VirtualGrid/HorizontalList.js'
import VerticalList from '../VirtualGrid/VerticalList.js'
import VerticalList1 from '../VirtualGrid/VerticalList1.js'
// import SeekBarWithPreview from '../VirtualList/SeekWithPreview.js'
// import VirtualizedSeekbarWithThumbnails from '../VirtualList/HorizontalList.js'
const data = [
    {
        "playListId": 285,
        "playlistName": "Top 10 Content - Testing",
        "playlistType": "ComingSoon",
        "height": "270",
        "width": "140",
        "playListTypeId": 7,
        "playlistItems": [
            {
                "totalRows": 10,
                "playListId": "285",
                "category": "Movies",
                "mediaID": "335",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Cheta Singh",
                "webThumbnail": "https://images.kableone.com/Images/MediaTest/1450250jpg_-1_0886.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/cheta-singhjpg-27375jpg_-2_02b9.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/MediaTest/11920-1080jpg_-3_63f9.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Cheta_Singh/master.m3u8",
                "shortDescription": "A common man Pala leads a very simple life working mainly on making his younger sister a well educated police officer. He can never harm anyone but one day his life turns upside down.",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Action, Drama, Thriller",
                "releasedYear": "2023",
                "ageRangeId": "UA 16",
                "duration": "1:0:0",
                "rating": 4.1,
                "preview_url": "https://media.kableone.com/Movies/Cheta_Singh/Videos/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 10,
                "playListId": "285",
                "category": "Movies",
                "mediaID": "318",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Khido Khundi",
                "webThumbnail": "https://images.kableone.com/Images/Media/Khido_Khundi_450_250_484e.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/khido-kundijpg_-2_3d4f.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/Khido_Khundi_1920_1080_f3db.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Khido_Khundi/master.m3u8",
                "shortDescription": "\"Khido Khundi\" is a 2018 Punjabi sports drama starring Ranjit Bawa, Mandy Takhar and Manav Vij. The film is centered on the sport of field hockey",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama, Sport",
                "releasedYear": "2018",
                "ageRangeId": "18",
                "duration": "2:32:00",
                "rating": 3.8,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Khido_Khundi/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 10,
                "playListId": "285",
                "category": "Movies",
                "mediaID": "378",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Ikko Mikke",
                "webThumbnail": "https://images.kableone.com/Images/MediaTest/IKKOMIKKE450X250jpg-11446%281%29png_-1_caa4.png?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/IKKOMIKKE303X430jpg-292fbavif_-2_174b.avif",
                "fullPageBanner": "https://images.kableone.com/Images/MediaTest/1-1920-10806738%281%29png_-3_a31e.png?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Ikko_Mikke/master.m3u8",
                "shortDescription": "",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Love, Drama",
                "releasedYear": "2025",
                "ageRangeId": "UA 13",
                "duration": "02:12:55",
                "rating": 3.5,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Ikko_Mikke/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 10,
                "playListId": "285",
                "category": "Movies",
                "mediaID": "282",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Snowman",
                "webThumbnail": "https://images.kableone.com/Images/MediaTest/snowman450x250-Copypng-10bb5jpeg_-1_ef75.jpeg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/snowmanjpg-2107ejpeg_-2_1597.jpeg",
                "fullPageBanner": "https://images.kableone.com/Images/MediaTest/snowmanpng-3c6a5jpeg_-3_10fa.jpeg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Snowman1/master.m3u8",
                "shortDescription": "\"Mundeyan Ton Bachke Rahin\" is a 2014 Punjabi romantic comedy featuring Roshan Prince, Jassi Gill, and Simran Kaur Mundi. The film revolves around two friends who, to win their love interests,",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Comedy, Romance",
                "releasedYear": "2014",
                "ageRangeId": "UA 7",
                "duration": "1:17:15",
                "rating": 2.6,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Snowman1/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 10,
                "playListId": "285",
                "category": "Movies",
                "mediaID": "209",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Asees",
                "webThumbnail": "https://images.kableone.com/Images/Media/asees450x250jpg_-1_81e9.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/aseesjpg_-2_b253.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/asees1920x1080jpg_-3_3604.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Asses/master.m3u8",
                "shortDescription": "\"Asees\" (2018) is a touching Punjabi drama portraying the bond between a mother and her son. The narrative unfolds against the backdrop of partition,",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama",
                "releasedYear": "2018",
                "ageRangeId": "A 18",
                "duration": "2:07:0",
                "rating": 4.4,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Asses/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 10,
                "playListId": "285",
                "category": "Movies",
                "mediaID": "330",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Lock",
                "webThumbnail": "https://images.kableone.com/Images/Media/1_0717.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/lockjpg_-2_99f1.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/1_e96e.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Lock/master.m3u8",
                "shortDescription": "Lock is a 2016 Punjabi crime thriller starring Gippy Grewal and Geeta Basra. The story centers around a man who is wrongly imprisoned for a crime he didn't commit.",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama, Thriller",
                "releasedYear": "2016",
                "ageRangeId": "13",
                "duration": "1:32:0",
                "rating": 3,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Lock/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 10,
                "playListId": "285",
                "category": "Music Video",
                "mediaID": "211",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "25 Pind",
                "webThumbnail": "https://images.kableone.com/Images/Media/maxresdefault%282%29_d290.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/Media/25Pind_3efd.jpg",
                "fullPageBanner": null,
                "logo": null,
                "trailerUrl": "test",
                "shortDescription": "",
                "categoryID": "3",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Love",
                "releasedYear": "2023",
                "ageRangeId": "UA 13",
                "duration": "0:0:0",
                "rating": 4.5,
                "preview_url": null,
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 10,
                "playListId": "285",
                "category": "Movies",
                "mediaID": "379",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Maa",
                "webThumbnail": "https://images.kableone.com/Images/MediaTest/MAApng-32e6favif_-1_0eab.avif?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/maajpg-2f642avif_-2_a840.avif",
                "fullPageBanner": "https://images.kableone.com/Images/MediaTest/Maa450x250png-19413jpeg_-3_a4bd.jpeg?im=Resize,width=1920",
                "logo": "https://images.kableone.com/Images/MediaTest/GPRadio8c2ejpg_-4_410b.jpg",
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Maa_Trailer/master.m3u8",
                "shortDescription": "",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Love, Sad, Drama",
                "releasedYear": "2025",
                "ageRangeId": "UA 13",
                "duration": "2:14:11",
                "rating": 3,
                "preview_url": "https://media.kableone.com/Movies/Maa/Videos/master_pa.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 10,
                "playListId": "285",
                "category": "Movies",
                "mediaID": "329",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "The Black Prince",
                "webThumbnail": "https://images.kableone.com/Images/Media/1_1888.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/Media/2_0b40.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/1_775a.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/The_Black_Prince/master.m3u8",
                "shortDescription": "The Black Prince (2017) narrates the poignant story of Maharaja Duleep Singh, the last Sikh ruler of Punjab, who was taken from his kingdom and raised in England.",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama, Historical",
                "releasedYear": "2017",
                "ageRangeId": "UA 7",
                "duration": "1:58:0",
                "rating": 3.8,
                "preview_url": "https://media.kableone.com/Previews/Trailer/The_Black_Prince/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 10,
                "playListId": "285",
                "category": "Movies",
                "mediaID": "327",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Judge Singh LLB",
                "webThumbnail": "https://images.kableone.com/Images/Media/1_024d.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/judge-singh-llbjpg_-2_26b0.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/1_6d49.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Karamsutra_Trailer/master.m3u8",
                "shortDescription": "Judge Singh LLB is a 2015 Punjabi legal comedy starring Ravinder Grewal, Surbhi Mahendru, and BN Sharma. The film follows Judge Singh, an eccentric and unorthodox lawyer, as he navigates",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama, Thriller",
                "releasedYear": "2015",
                "ageRangeId": "UA 13",
                "duration": "2:17:0",
                "rating": 4.2,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Karamsutra_Trailer/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            }
        ]
    },
    {
        "playListId": 286,
        "playlistName": "Web Series 2",
        "playlistType": "ComingSoon",
        "height": "270",
        "width": "140",
        "playListTypeId": 7,
        "playlistItems": [
            {
                "totalRows": 3,
                "playListId": "286",
                "category": "Web Series",
                "mediaID": "392",
                "webSeriesID": "86",
                "webSeriesName": "Aao Sangat Kariye",
                "title": "First second third fourth",
                "webThumbnail": "https://images.kableone.com/Images/MediaTest/EP4ASK450X250jpg_-1_79a6.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/MGOLEMAILER140x270jpg_7_5b7e.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/MediaTest/192010803Imagesjpg_-3_0a3d.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Aao_Sangat_Kariye_Trailer3/master.m3u8",
                "shortDescription": "Hosts Harbir Kaur and Gurkaran Singh welcomes sikh scholars and thinkers to impart their wisdom on sikh heritage and converse about the lives of the guru sahibaans.",
                "categoryID": "2",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Historical",
                "releasedYear": "2025",
                "ageRangeId": "UA 13",
                "duration": "0:47:0",
                "rating": 3,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Aao_Sangat_Kariye_Trailer3/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 3,
                "playListId": "286",
                "category": "Web Series",
                "mediaID": "393",
                "webSeriesID": "86",
                "webSeriesName": "Aao Sangat Kariye",
                "title": "Episode 05",
                "webThumbnail": "https://images.kableone.com/Images/MediaTest/EP5ASK450X250jpg_-1_a02f.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/MGOLEMAILER140x270jpg_7_53b1.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/MediaTest/192010803Imagesjpg_-3_9165.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Aao_Sangat_Kariye_Trailer3/master.m3u8",
                "shortDescription": "Hosts Harbir Kaur and Gurkaran Singh welcomes sikh scholars and thinkers to impart their wisdom on sikh heritage and converse about the lives of the guru sahibaans.",
                "categoryID": "2",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Historical",
                "releasedYear": "2025",
                "ageRangeId": "UA 13",
                "duration": "00:35:51",
                "rating": 3,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Aao_Sangat_Kariye_Trailer3/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 3,
                "playListId": "286",
                "category": "Web Series",
                "mediaID": "394",
                "webSeriesID": "86",
                "webSeriesName": "Aao Sangat Kariye",
                "title": "Episode 06",
                "webThumbnail": "https://images.kableone.com/Images/MediaTest/EP6ASK450X250jpg_-1_ef2e.jpg?im=Resize,width=450",
                "mobileThumbnail": null,
                "fullPageBanner": "https://images.kableone.com/Images/MediaTest/192010804Imagesjpg_-3_7a38.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Aao_Sangat_Kariye_Trailer3/master.m3u8",
                "shortDescription": "Hosts Harbir Kaur and Gurkaran Singh welcomes sikh scholars and thinkers to impart their wisdom on sikh heritage and converse about the lives of the guru sahibaans.",
                "categoryID": "2",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Historical",
                "releasedYear": "2025",
                "ageRangeId": "UA 13",
                "duration": "0:50:0",
                "rating": 3,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Aao_Sangat_Kariye_Trailer3/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": true
            }
        ]
    },
    {
        "playListId": 278,
        "playlistName": "Kableone Series",
        "playlistType": "Original",
        "height": "120",
        "width": "120",
        "playListTypeId": 9,
        "playlistItems": [
            {
                "totalRows": 2,
                "playListId": "278",
                "category": "Web Series",
                "mediaID": "389",
                "webSeriesID": "86",
                "webSeriesName": "Aao Sangat Kariye",
                "title": "Episode 01",
                "webThumbnail": "https://images.kableone.com/Images/MediaTest/EP1ASK450X250jpg_-1_7102.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/300x300jpg_9_5231.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/MediaTest/19201080Imagesjpg_-3_5168.jpg?im=Resize,width=1920",
                "logo": "https://images.kableone.com/Images/MediaTest/SagaMusicRadioa50apng_-4_17e9.png",
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Aao_Sangat_Kariye_Trailer3/master.m3u8",
                "shortDescription": "Hosts Harbir Kaur and Gurkaran Singh welcomes sikh scholars and thinkers to impart their wisdom on sikh heritage and converse about the lives of the guru sahibaans.",
                "categoryID": "2",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Historical",
                "releasedYear": "2025",
                "ageRangeId": "UA 13",
                "duration": "01:55:00",
                "rating": 3,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Aao_Sangat_Kariye_Trailer3/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": true
            },
            {
                "totalRows": 2,
                "playListId": "278",
                "category": "Web Series",
                "mediaID": "395",
                "webSeriesID": "87",
                "webSeriesName": "The Sattinder Satti Show",
                "title": "The Satinder Satti Show_EP01",
                "webThumbnail": "https://images.kableone.com/Images/MediaTest/SSS450X250jpg_-1_c31b.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/300X300jpg_9_97a6.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/MediaTest/SSShow1920X1006jpg_-3_c347.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": null,
                "shortDescription": "",
                "categoryID": "2",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Fantasy",
                "releasedYear": "2025",
                "ageRangeId": "UA 13",
                "duration": "0:44:0",
                "rating": 3,
                "preview_url": null,
                "isMediaPublished": true,
                "openWebSeries": false
            }
        ]
    },
    {
        "playListId": 182,
        "playlistName": "Only on Kableone",
        "playlistType": "Default",
        "height": "155",
        "width": "110",
        "playListTypeId": 8,
        "playlistItems": [
            {
                "totalRows": 13,
                "playListId": "182",
                "category": "Movies",
                "mediaID": "275",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Manje Bistre",
                "webThumbnail": "https://images.kableone.com/Images/Media/Manje_Bistre_450_250_24a8.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/Media/Manjebistre303430jpg_8_842f.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/Manje_Bistre_1920_1080_db21.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": null,
                "shortDescription": "\"Manje Bistre\" is a Punjabi comedy-drama that revolves around a traditional Punjabi wedding. Filled with humor, it depicts the clash of rural and urban cultures,",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Comedy, Drama",
                "releasedYear": "2017",
                "ageRangeId": "18",
                "duration": "2:17:0",
                "rating": 4,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Manje_Bistre/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 13,
                "playListId": "182",
                "category": "Movies",
                "mediaID": "282",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Snowman",
                "webThumbnail": "https://images.kableone.com/Images/MediaTest/snowman450x250-Copypng-10bb5jpeg_-1_ef75.jpeg?im=Resize,width=450",
                "mobileThumbnail": null,
                "fullPageBanner": "https://images.kableone.com/Images/MediaTest/snowmanpng-3c6a5jpeg_-3_10fa.jpeg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Snowman1/master.m3u8",
                "shortDescription": "\"Mundeyan Ton Bachke Rahin\" is a 2014 Punjabi romantic comedy featuring Roshan Prince, Jassi Gill, and Simran Kaur Mundi. The film revolves around two friends who, to win their love interests,",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Comedy, Romance",
                "releasedYear": "2014",
                "ageRangeId": "UA 7",
                "duration": "1:17:15",
                "rating": 2.6,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Snowman1/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 13,
                "playListId": "182",
                "category": "Movies",
                "mediaID": "292",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Dil Vil Pyaar Vyaar",
                "webThumbnail": "https://images.kableone.com/Images/Media/Dil_Vil_Pyaar_Vyaar_450_250_8e8c.jpg?im=Resize,width=450",
                "mobileThumbnail": null,
                "fullPageBanner": "https://images.kableone.com/Images/Media/Dil_Vil_Pyaar_Vyaar_1920_1080_599a.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Dil_Vil_Pyaar_Vyaar/master.m3u8",
                "shortDescription": "\"Dil Vil Pyaar Vyaar\" is a 2014 Punjabi romantic drama starring Gurdas Maan, Neeru Bajwa, Jassie Gill and Juhi Chawla. The film weaves a tale of love, friendship,",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama, Family",
                "releasedYear": "2023",
                "ageRangeId": "13",
                "duration": "2:25:0",
                "rating": 3.7,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Dil_Vil_Pyaar_Vyaar/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 13,
                "playListId": "182",
                "category": "Movies",
                "mediaID": "317",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Dushman",
                "webThumbnail": "https://images.kableone.com/Images/Media/Dushman_450_250_ed71.jpg?im=Resize,width=450",
                "mobileThumbnail": null,
                "fullPageBanner": "https://images.kableone.com/Images/Media/Dushman_1920_1080_1739.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Dushman/master.m3u8",
                "shortDescription": "\"Dushman\" is a 2017 Punjabi psychological thriller starring Kartar Cheema and Jashan Singh. The film delves into the complexities of human relationships",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama",
                "releasedYear": "2023",
                "ageRangeId": "18",
                "duration": "2:23:0",
                "rating": 2.4,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Dushman/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 13,
                "playListId": "182",
                "category": "Movies",
                "mediaID": "318",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Khido Khundi",
                "webThumbnail": "https://images.kableone.com/Images/Media/Khido_Khundi_450_250_484e.jpg?im=Resize,width=450",
                "mobileThumbnail": null,
                "fullPageBanner": "https://images.kableone.com/Images/Media/Khido_Khundi_1920_1080_f3db.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Khido_Khundi/master.m3u8",
                "shortDescription": "\"Khido Khundi\" is a 2018 Punjabi sports drama starring Ranjit Bawa, Mandy Takhar and Manav Vij. The film is centered on the sport of field hockey",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama, Sport",
                "releasedYear": "2018",
                "ageRangeId": "18",
                "duration": "2:32:00",
                "rating": 3.8,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Khido_Khundi/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 13,
                "playListId": "182",
                "category": "Movies",
                "mediaID": "323",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Gaddar : The Traitor",
                "webThumbnail": "https://images.kableone.com/Images/Media/1_0105.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/Media/1jpg_8_ed89.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/1_48cc.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Gurmukh_Trailer_1/master_pa.m3u8",
                "shortDescription": "Gaddar: The Traitor is a 2015 Punjabi thriller starring Harbhajan Mann, Manpneet Grewal, and Evelyn Sharma. The film revolves around a man caught in a web of deceit",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama, Thriller",
                "releasedYear": "2023",
                "ageRangeId": "18",
                "duration": "2:6:0",
                "rating": 3.6,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Gurmukh_Trailer_1/master_pa.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 13,
                "playListId": "182",
                "category": "Movies",
                "mediaID": "327",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Judge Singh LLB",
                "webThumbnail": "https://images.kableone.com/Images/Media/1_024d.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/Media/1jpg_8_5774.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/1_6d49.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Karamsutra_Trailer/master.m3u8",
                "shortDescription": "Judge Singh LLB is a 2015 Punjabi legal comedy starring Ravinder Grewal, Surbhi Mahendru, and BN Sharma. The film follows Judge Singh, an eccentric and unorthodox lawyer, as he navigates",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama, Thriller",
                "releasedYear": "2015",
                "ageRangeId": "UA 13",
                "duration": "2:17:0",
                "rating": 4.2,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Karamsutra_Trailer/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 13,
                "playListId": "182",
                "category": "Movies",
                "mediaID": "328",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Laatu",
                "webThumbnail": "https://images.kableone.com/Images/Media/1_481c.jpg?im=Resize,width=450",
                "mobileThumbnail": null,
                "fullPageBanner": "https://images.kableone.com/Images/Media/1_31c0.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Laatu/master.m3u8",
                "shortDescription": "Laatu is a 2018 Punjabi drama featuring Gagan Kokri, Aditi Sharma, and Karamjit Anmol. Set in a rural village, it addresses the issue of electricity scarcity.",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama",
                "releasedYear": "2018",
                "ageRangeId": "13",
                "duration": "1:52:0",
                "rating": 3.8,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Laatu/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 13,
                "playListId": "182",
                "category": "Movies",
                "mediaID": "329",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "The Black Prince",
                "webThumbnail": "https://images.kableone.com/Images/Media/1_1888.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/Media/2jpg_8_d277.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/1_775a.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/The_Black_Prince/master.m3u8",
                "shortDescription": "The Black Prince (2017) narrates the poignant story of Maharaja Duleep Singh, the last Sikh ruler of Punjab, who was taken from his kingdom and raised in England.",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama, Historical",
                "releasedYear": "2017",
                "ageRangeId": "UA 7",
                "duration": "1:58:0",
                "rating": 3.8,
                "preview_url": "https://media.kableone.com/Previews/Trailer/The_Black_Prince/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 13,
                "playListId": "182",
                "category": "Movies",
                "mediaID": "330",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Lock",
                "webThumbnail": "https://images.kableone.com/Images/Media/1_0717.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/Media/1jpg_8_d264.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/1_e96e.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Lock/master.m3u8",
                "shortDescription": "Lock is a 2016 Punjabi crime thriller starring Gippy Grewal and Geeta Basra. The story centers around a man who is wrongly imprisoned for a crime he didn't commit.",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama, Thriller",
                "releasedYear": "2016",
                "ageRangeId": "13",
                "duration": "1:32:0",
                "rating": 3,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Lock/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 13,
                "playListId": "182",
                "category": "Movies",
                "mediaID": "330",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Lock",
                "webThumbnail": "https://images.kableone.com/Images/Media/1_0717.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/Media/1jpg_8_d264.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/1_e96e.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Lock/master.m3u8",
                "shortDescription": "Lock is a 2016 Punjabi crime thriller starring Gippy Grewal and Geeta Basra. The story centers around a man who is wrongly imprisoned for a crime he didn't commit.",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama, Thriller",
                "releasedYear": "2016",
                "ageRangeId": "13",
                "duration": "1:32:0",
                "rating": 3,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Lock/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false,
                "isSeeMore": true,
                "bgHplColor": "black"
            }
        ]
    },
    {
        "playListId": 181,
        "playlistName": "New Releases",
        "playlistType": "Original",
        "height": "120",
        "width": "120",
        "playListTypeId": 9,
        "playlistItems": [
            {
                "totalRows": 8,
                "playListId": "181",
                "category": "Movies",
                "mediaID": "209",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Asees",
                "webThumbnail": "https://images.kableone.com/Images/Media/asees450x250jpg_-1_81e9.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/Media/218x2172jpg_9_0b0f.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/asees1920x1080jpg_-3_3604.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Asses/master.m3u8",
                "shortDescription": "\"Asees\" (2018) is a touching Punjabi drama portraying the bond between a mother and her son. The narrative unfolds against the backdrop of partition,",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama",
                "releasedYear": "2018",
                "ageRangeId": "A 18",
                "duration": "2:07:0",
                "rating": 4.4,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Asses/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 8,
                "playListId": "181",
                "category": "Movies",
                "mediaID": "282",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Snowman",
                "webThumbnail": "https://images.kableone.com/Images/MediaTest/snowman450x250-Copypng-10bb5jpeg_-1_ef75.jpeg?im=Resize,width=450",
                "mobileThumbnail": null,
                "fullPageBanner": "https://images.kableone.com/Images/MediaTest/snowmanpng-3c6a5jpeg_-3_10fa.jpeg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Snowman1/master.m3u8",
                "shortDescription": "\"Mundeyan Ton Bachke Rahin\" is a 2014 Punjabi romantic comedy featuring Roshan Prince, Jassi Gill, and Simran Kaur Mundi. The film revolves around two friends who, to win their love interests,",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Comedy, Romance",
                "releasedYear": "2014",
                "ageRangeId": "UA 7",
                "duration": "1:17:15",
                "rating": 2.6,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Snowman1/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 8,
                "playListId": "181",
                "category": "Movies",
                "mediaID": "292",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Dil Vil Pyaar Vyaar",
                "webThumbnail": "https://images.kableone.com/Images/Media/Dil_Vil_Pyaar_Vyaar_450_250_8e8c.jpg?im=Resize,width=450",
                "mobileThumbnail": null,
                "fullPageBanner": "https://images.kableone.com/Images/Media/Dil_Vil_Pyaar_Vyaar_1920_1080_599a.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Dil_Vil_Pyaar_Vyaar/master.m3u8",
                "shortDescription": "\"Dil Vil Pyaar Vyaar\" is a 2014 Punjabi romantic drama starring Gurdas Maan, Neeru Bajwa, Jassie Gill and Juhi Chawla. The film weaves a tale of love, friendship,",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama, Family",
                "releasedYear": "2023",
                "ageRangeId": "13",
                "duration": "2:25:0",
                "rating": 3.7,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Dil_Vil_Pyaar_Vyaar/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 8,
                "playListId": "181",
                "category": "Movies",
                "mediaID": "317",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Dushman",
                "webThumbnail": "https://images.kableone.com/Images/Media/Dushman_450_250_ed71.jpg?im=Resize,width=450",
                "mobileThumbnail": null,
                "fullPageBanner": "https://images.kableone.com/Images/Media/Dushman_1920_1080_1739.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Dushman/master.m3u8",
                "shortDescription": "\"Dushman\" is a 2017 Punjabi psychological thriller starring Kartar Cheema and Jashan Singh. The film delves into the complexities of human relationships",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama",
                "releasedYear": "2023",
                "ageRangeId": "18",
                "duration": "2:23:0",
                "rating": 2.4,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Dushman/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 8,
                "playListId": "181",
                "category": "Movies",
                "mediaID": "322",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Faraar",
                "webThumbnail": "https://images.kableone.com/Images/Media/1_4a93.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/Media/218x2171jpg_9_e8b2.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/1_7485.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Gurmukh_Trailer_1/master_pa.m3u8",
                "shortDescription": "Faraar is a 2015 Punjabi action-thriller starring Gippy Grewal and Kainaat Arora. The film follows a man wrongly accused of a crime he didn't commit",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Action",
                "releasedYear": "2015",
                "ageRangeId": "UA 16",
                "duration": "2:28:0",
                "rating": 2.3,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Gurmukh_Trailer_1/master_pa.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 8,
                "playListId": "181",
                "category": "Movies",
                "mediaID": "323",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Gaddar : The Traitor",
                "webThumbnail": "https://images.kableone.com/Images/Media/1_0105.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/Media/218x2172jpg_9_5c50.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/1_48cc.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Gurmukh_Trailer_1/master_pa.m3u8",
                "shortDescription": "Gaddar: The Traitor is a 2015 Punjabi thriller starring Harbhajan Mann, Manpneet Grewal, and Evelyn Sharma. The film revolves around a man caught in a web of deceit",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama, Thriller",
                "releasedYear": "2023",
                "ageRangeId": "18",
                "duration": "2:6:0",
                "rating": 3.6,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Gurmukh_Trailer_1/master_pa.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 8,
                "playListId": "181",
                "category": "Movies",
                "mediaID": "333",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Parchi",
                "webThumbnail": "https://images.kableone.com/Images/Media/1_db1c.jpg?im=Resize,width=450",
                "mobileThumbnail": null,
                "fullPageBanner": "https://images.kableone.com/Images/Media/1_7ef5.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Movies/Parchi/Videos/master.m3u8",
                "shortDescription": "Parchi is a 2018 Pakistani black comedy film featuring Hareem Farooq, Ali Rehman Khan, and Ahmed Ali Akbar. The story revolves around a group of friends who become entangled with a local gangster",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Comedy, Drama",
                "releasedYear": "2018",
                "ageRangeId": "13",
                "duration": "2:17:0",
                "rating": 2.6,
                "preview_url": null,
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 8,
                "playListId": "181",
                "category": "Movies",
                "mediaID": "337",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Zindagi Zindabad",
                "webThumbnail": "https://images.kableone.com/Images/MediaTest/1450250jpg_-1_ed64.jpg?im=Resize,width=450",
                "mobileThumbnail": null,
                "fullPageBanner": "https://images.kableone.com/Images/MediaTest/119201080jpg_-3_0116.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Zindagi_Zindabaad/master.m3u8",
                "shortDescription": "just for testing",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Action",
                "releasedYear": "2023",
                "ageRangeId": "13",
                "duration": "0:0:0",
                "rating": 4,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Zindagi_Zindabaad/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            }
        ]
    },
    {
        "playListId": 237,
        "playlistName": "Action Movies",
        "playlistType": null,
        "height": null,
        "width": null,
        "playListTypeId": 0,
        "playlistItems": [
            {
                "totalRows": 10,
                "playListId": "237",
                "category": "Movies",
                "mediaID": "282",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Snowman",
                "webThumbnail": "https://images.kableone.com/Images/MediaTest/snowman450x250-Copypng-10bb5jpeg_-1_ef75.jpeg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/snowmanjpg-2107ejpeg_-2_1597.jpeg",
                "fullPageBanner": "https://images.kableone.com/Images/MediaTest/snowmanpng-3c6a5jpeg_-3_10fa.jpeg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Snowman1/master.m3u8",
                "shortDescription": "\"Mundeyan Ton Bachke Rahin\" is a 2014 Punjabi romantic comedy featuring Roshan Prince, Jassi Gill, and Simran Kaur Mundi. The film revolves around two friends who, to win their love interests,",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Comedy, Romance",
                "releasedYear": "2014",
                "ageRangeId": "UA 7",
                "duration": "1:17:15",
                "rating": 2.6,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Snowman1/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 10,
                "playListId": "237",
                "category": "Movies",
                "mediaID": "292",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Dil Vil Pyaar Vyaar",
                "webThumbnail": "https://images.kableone.com/Images/Media/Dil_Vil_Pyaar_Vyaar_450_250_8e8c.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/dilvil-pyar-vyarjpg_-2_5408.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/Dil_Vil_Pyaar_Vyaar_1920_1080_599a.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Dil_Vil_Pyaar_Vyaar/master.m3u8",
                "shortDescription": "\"Dil Vil Pyaar Vyaar\" is a 2014 Punjabi romantic drama starring Gurdas Maan, Neeru Bajwa, Jassie Gill and Juhi Chawla. The film weaves a tale of love, friendship,",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama, Family",
                "releasedYear": "2023",
                "ageRangeId": "13",
                "duration": "2:25:0",
                "rating": 3.7,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Dil_Vil_Pyaar_Vyaar/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 10,
                "playListId": "237",
                "category": "Movies",
                "mediaID": "317",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Dushman",
                "webThumbnail": "https://images.kableone.com/Images/Media/Dushman_450_250_ed71.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/dushamnajpg_-2_ee5e.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/Dushman_1920_1080_1739.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Dushman/master.m3u8",
                "shortDescription": "\"Dushman\" is a 2017 Punjabi psychological thriller starring Kartar Cheema and Jashan Singh. The film delves into the complexities of human relationships",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama",
                "releasedYear": "2023",
                "ageRangeId": "18",
                "duration": "2:23:0",
                "rating": 2.4,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Dushman/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 10,
                "playListId": "237",
                "category": "Movies",
                "mediaID": "318",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Khido Khundi",
                "webThumbnail": "https://images.kableone.com/Images/Media/Khido_Khundi_450_250_484e.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/khido-kundijpg_-2_3d4f.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/Khido_Khundi_1920_1080_f3db.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Khido_Khundi/master.m3u8",
                "shortDescription": "\"Khido Khundi\" is a 2018 Punjabi sports drama starring Ranjit Bawa, Mandy Takhar and Manav Vij. The film is centered on the sport of field hockey",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama, Sport",
                "releasedYear": "2018",
                "ageRangeId": "18",
                "duration": "2:32:00",
                "rating": 3.8,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Khido_Khundi/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 10,
                "playListId": "237",
                "category": "Movies",
                "mediaID": "321",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Bathinda Express",
                "webThumbnail": "https://images.kableone.com/Images/Media/1_4220.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/bhatinda-expressjpg_-2_41c2.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/1_d1da.jpg?im=Resize,width=1920",
                "logo": "https://images.kableone.com/Images/MediaTest/tevelisionjpg_-4_2979.jpg",
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Bathinda_Express/master.m3u8",
                "shortDescription": "Bathinda Express is a 2016 Punjabi sports drama starring Deep Joshi and Jasmine Kaur. The film revolves around a young aspiring athlete from Bathinda",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama",
                "releasedYear": "2016",
                "ageRangeId": "UA 13",
                "duration": "2:2:0",
                "rating": 2.6,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Bathinda_Express/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 10,
                "playListId": "237",
                "category": "Movies",
                "mediaID": "322",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Faraar",
                "webThumbnail": "https://images.kableone.com/Images/Media/1_4a93.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/faraarjpg_-2_bd5e.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/1_7485.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Gurmukh_Trailer_1/master_pa.m3u8",
                "shortDescription": "Faraar is a 2015 Punjabi action-thriller starring Gippy Grewal and Kainaat Arora. The film follows a man wrongly accused of a crime he didn't commit",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Action",
                "releasedYear": "2015",
                "ageRangeId": "UA 16",
                "duration": "2:28:0",
                "rating": 2.3,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Gurmukh_Trailer_1/master_pa.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 10,
                "playListId": "237",
                "category": "Movies",
                "mediaID": "327",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Judge Singh LLB",
                "webThumbnail": "https://images.kableone.com/Images/Media/1_024d.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/judge-singh-llbjpg_-2_26b0.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/1_6d49.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Karamsutra_Trailer/master.m3u8",
                "shortDescription": "Judge Singh LLB is a 2015 Punjabi legal comedy starring Ravinder Grewal, Surbhi Mahendru, and BN Sharma. The film follows Judge Singh, an eccentric and unorthodox lawyer, as he navigates",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama, Thriller",
                "releasedYear": "2015",
                "ageRangeId": "UA 13",
                "duration": "2:17:0",
                "rating": 4.2,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Karamsutra_Trailer/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 10,
                "playListId": "237",
                "category": "Movies",
                "mediaID": "358",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Sucha Soorma Chinese",
                "webThumbnail": "https://images.kableone.com/Images/MediaTest/Chinesejpg_-1_22f4.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/303X430Chinesejpg_-2_0b09.jpg",
                "fullPageBanner": null,
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Sucha_Soorma_Trailer/master_zh.m3u8",
                "shortDescription": null,
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Action, Drama",
                "releasedYear": "2024",
                "ageRangeId": "13",
                "duration": "0:0:0",
                "rating": null,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Sucha_Soorma_Trailer/master_zh.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 10,
                "playListId": "237",
                "category": "Movies",
                "mediaID": "363",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Sucha Soorma Russian ",
                "webThumbnail": "https://images.kableone.com/Images/MediaTest/Russianjpg_-1_a0c5.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/303X430Russianjpg_-2_11c2.jpg",
                "fullPageBanner": null,
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Sucha_Soorma_Trailer/master_ru.m3u8",
                "shortDescription": null,
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Action, Drama",
                "releasedYear": "2024",
                "ageRangeId": "13",
                "duration": "0:0:0",
                "rating": null,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Sucha_Soorma_Trailer/master_ru.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 10,
                "playListId": "237",
                "category": "Movies",
                "mediaID": "364",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Sucha Soorma Tamil",
                "webThumbnail": "https://images.kableone.com/Images/MediaTest/Tamiljpg_-1_4c2e.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/303X430Tamiljpg_-2_84c8.jpg",
                "fullPageBanner": null,
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Sucha_Soorma_Trailer/master_ta.m3u8",
                "shortDescription": null,
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Action, Drama",
                "releasedYear": "2024",
                "ageRangeId": "13",
                "duration": "0:0:0",
                "rating": null,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Sucha_Soorma_Trailer/master_ta.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            }
        ]
    },
    {
        "playListId": 199,
        "playlistName": "Punjabi  Movies",
        "playlistType": null,
        "height": null,
        "width": null,
        "playListTypeId": 0,
        "playlistItems": [
            {
                "totalRows": 22,
                "playListId": "199",
                "category": "Movies",
                "mediaID": "209",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Asees",
                "webThumbnail": "https://images.kableone.com/Images/Media/asees450x250jpg_-1_81e9.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/aseesjpg_-2_b253.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/asees1920x1080jpg_-3_3604.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Asses/master.m3u8",
                "shortDescription": "\"Asees\" (2018) is a touching Punjabi drama portraying the bond between a mother and her son. The narrative unfolds against the backdrop of partition,",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama",
                "releasedYear": "2018",
                "ageRangeId": "A 18",
                "duration": "2:07:0",
                "rating": 4.4,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Asses/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 22,
                "playListId": "199",
                "category": "Movies",
                "mediaID": "282",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Snowman",
                "webThumbnail": "https://images.kableone.com/Images/MediaTest/snowman450x250-Copypng-10bb5jpeg_-1_ef75.jpeg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/snowmanjpg-2107ejpeg_-2_1597.jpeg",
                "fullPageBanner": "https://images.kableone.com/Images/MediaTest/snowmanpng-3c6a5jpeg_-3_10fa.jpeg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Snowman1/master.m3u8",
                "shortDescription": "\"Mundeyan Ton Bachke Rahin\" is a 2014 Punjabi romantic comedy featuring Roshan Prince, Jassi Gill, and Simran Kaur Mundi. The film revolves around two friends who, to win their love interests,",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Comedy, Romance",
                "releasedYear": "2014",
                "ageRangeId": "UA 7",
                "duration": "1:17:15",
                "rating": 2.6,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Snowman1/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 22,
                "playListId": "199",
                "category": "Movies",
                "mediaID": "292",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Dil Vil Pyaar Vyaar",
                "webThumbnail": "https://images.kableone.com/Images/Media/Dil_Vil_Pyaar_Vyaar_450_250_8e8c.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/dilvil-pyar-vyarjpg_-2_5408.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/Dil_Vil_Pyaar_Vyaar_1920_1080_599a.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Dil_Vil_Pyaar_Vyaar/master.m3u8",
                "shortDescription": "\"Dil Vil Pyaar Vyaar\" is a 2014 Punjabi romantic drama starring Gurdas Maan, Neeru Bajwa, Jassie Gill and Juhi Chawla. The film weaves a tale of love, friendship,",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama, Family",
                "releasedYear": "2023",
                "ageRangeId": "13",
                "duration": "2:25:0",
                "rating": 3.7,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Dil_Vil_Pyaar_Vyaar/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 22,
                "playListId": "199",
                "category": "Movies",
                "mediaID": "317",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Dushman",
                "webThumbnail": "https://images.kableone.com/Images/Media/Dushman_450_250_ed71.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/dushamnajpg_-2_ee5e.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/Dushman_1920_1080_1739.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Dushman/master.m3u8",
                "shortDescription": "\"Dushman\" is a 2017 Punjabi psychological thriller starring Kartar Cheema and Jashan Singh. The film delves into the complexities of human relationships",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama",
                "releasedYear": "2023",
                "ageRangeId": "18",
                "duration": "2:23:0",
                "rating": 2.4,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Dushman/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 22,
                "playListId": "199",
                "category": "Movies",
                "mediaID": "318",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Khido Khundi",
                "webThumbnail": "https://images.kableone.com/Images/Media/Khido_Khundi_450_250_484e.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/khido-kundijpg_-2_3d4f.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/Khido_Khundi_1920_1080_f3db.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Khido_Khundi/master.m3u8",
                "shortDescription": "\"Khido Khundi\" is a 2018 Punjabi sports drama starring Ranjit Bawa, Mandy Takhar and Manav Vij. The film is centered on the sport of field hockey",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama, Sport",
                "releasedYear": "2018",
                "ageRangeId": "18",
                "duration": "2:32:00",
                "rating": 3.8,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Khido_Khundi/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 22,
                "playListId": "199",
                "category": "Movies",
                "mediaID": "321",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Bathinda Express",
                "webThumbnail": "https://images.kableone.com/Images/Media/1_4220.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/bhatinda-expressjpg_-2_41c2.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/1_d1da.jpg?im=Resize,width=1920",
                "logo": "https://images.kableone.com/Images/MediaTest/tevelisionjpg_-4_2979.jpg",
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Bathinda_Express/master.m3u8",
                "shortDescription": "Bathinda Express is a 2016 Punjabi sports drama starring Deep Joshi and Jasmine Kaur. The film revolves around a young aspiring athlete from Bathinda",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama",
                "releasedYear": "2016",
                "ageRangeId": "UA 13",
                "duration": "2:2:0",
                "rating": 2.6,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Bathinda_Express/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 22,
                "playListId": "199",
                "category": "Movies",
                "mediaID": "322",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Faraar",
                "webThumbnail": "https://images.kableone.com/Images/Media/1_4a93.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/faraarjpg_-2_bd5e.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/1_7485.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Gurmukh_Trailer_1/master_pa.m3u8",
                "shortDescription": "Faraar is a 2015 Punjabi action-thriller starring Gippy Grewal and Kainaat Arora. The film follows a man wrongly accused of a crime he didn't commit",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Action",
                "releasedYear": "2015",
                "ageRangeId": "UA 16",
                "duration": "2:28:0",
                "rating": 2.3,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Gurmukh_Trailer_1/master_pa.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 22,
                "playListId": "199",
                "category": "Movies",
                "mediaID": "323",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Gaddar : The Traitor",
                "webThumbnail": "https://images.kableone.com/Images/Media/1_0105.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/gaddarjpg_-2_4055.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/1_48cc.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Gurmukh_Trailer_1/master_pa.m3u8",
                "shortDescription": "Gaddar: The Traitor is a 2015 Punjabi thriller starring Harbhajan Mann, Manpneet Grewal, and Evelyn Sharma. The film revolves around a man caught in a web of deceit",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama, Thriller",
                "releasedYear": "2023",
                "ageRangeId": "18",
                "duration": "2:6:0",
                "rating": 3.6,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Gurmukh_Trailer_1/master_pa.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 22,
                "playListId": "199",
                "category": "Movies",
                "mediaID": "324",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Gumm",
                "webThumbnail": "https://images.kableone.com/Images/Media/1_f0f7.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/gummjpg_-2_dad4.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/1_a6e1.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Gumm/master.m3u8",
                "shortDescription": "Gumm is a 2019 Pakistani thriller starring Sami Khan and Shamoon Abbasi. The film revolves around an adventurous road trip that takes an ominous turn",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Action, Drama, Romance",
                "releasedYear": "2019",
                "ageRangeId": "13",
                "duration": "1:50:0",
                "rating": 4.2,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Gumm/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 22,
                "playListId": "199",
                "category": "Movies",
                "mediaID": "327",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Judge Singh LLB",
                "webThumbnail": "https://images.kableone.com/Images/Media/1_024d.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/judge-singh-llbjpg_-2_26b0.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/1_6d49.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Karamsutra_Trailer/master.m3u8",
                "shortDescription": "Judge Singh LLB is a 2015 Punjabi legal comedy starring Ravinder Grewal, Surbhi Mahendru, and BN Sharma. The film follows Judge Singh, an eccentric and unorthodox lawyer, as he navigates",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama, Thriller",
                "releasedYear": "2015",
                "ageRangeId": "UA 13",
                "duration": "2:17:0",
                "rating": 4.2,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Karamsutra_Trailer/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 22,
                "playListId": "199",
                "category": "Movies",
                "mediaID": "327",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Judge Singh LLB",
                "webThumbnail": "https://images.kableone.com/Images/Media/1_024d.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/judge-singh-llbjpg_-2_26b0.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/1_6d49.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Karamsutra_Trailer/master.m3u8",
                "shortDescription": "Judge Singh LLB is a 2015 Punjabi legal comedy starring Ravinder Grewal, Surbhi Mahendru, and BN Sharma. The film follows Judge Singh, an eccentric and unorthodox lawyer, as he navigates",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama, Thriller",
                "releasedYear": "2015",
                "ageRangeId": "UA 13",
                "duration": "2:17:0",
                "rating": 4.2,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Karamsutra_Trailer/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false,
                "isSeeMore": true,
                "bgHplColor": "black"
            }
        ]
    },
    {
        "playListId": 200,
        "playlistName": "Top 10 Movies ",
        "playlistType": null,
        "height": null,
        "width": null,
        "playListTypeId": 0,
        "playlistItems": [
            {
                "totalRows": 3,
                "playListId": "200",
                "category": "Movies",
                "mediaID": "327",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Judge Singh LLB",
                "webThumbnail": "https://images.kableone.com/Images/Media/1_024d.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/judge-singh-llbjpg_-2_26b0.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/1_6d49.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Karamsutra_Trailer/master.m3u8",
                "shortDescription": "Judge Singh LLB is a 2015 Punjabi legal comedy starring Ravinder Grewal, Surbhi Mahendru, and BN Sharma. The film follows Judge Singh, an eccentric and unorthodox lawyer, as he navigates",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama, Thriller",
                "releasedYear": "2015",
                "ageRangeId": "UA 13",
                "duration": "2:17:0",
                "rating": 4.2,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Karamsutra_Trailer/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 3,
                "playListId": "200",
                "category": "Movies",
                "mediaID": "328",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Laatu",
                "webThumbnail": "https://images.kableone.com/Images/Media/1_481c.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/laatujpg_-2_f4ea.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/1_31c0.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Laatu/master.m3u8",
                "shortDescription": "Laatu is a 2018 Punjabi drama featuring Gagan Kokri, Aditi Sharma, and Karamjit Anmol. Set in a rural village, it addresses the issue of electricity scarcity.",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama",
                "releasedYear": "2018",
                "ageRangeId": "13",
                "duration": "1:52:0",
                "rating": 3.8,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Laatu/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 3,
                "playListId": "200",
                "category": "Movies",
                "mediaID": "331",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Motor Mitraan Di",
                "webThumbnail": "https://images.kableone.com/Images/Media/1_2ec4.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/motor-mitraan-dijpg_-2_649e.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/1_27c3.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Motor_Mitraan_Di/master.m3u8",
                "shortDescription": "Motor Mitraan Di is a 2016 Punjabi comedy film starring Gurpreet Ghuggi, Happy Raikoti, and Sonia Mann. The story revolves around a family's love for their jeep",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Comedy, Drama",
                "releasedYear": "2016",
                "ageRangeId": "13",
                "duration": "1:57:0",
                "rating": 3.2,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Motor_Mitraan_Di/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            }
        ]
    },
    {
        "playListId": 239,
        "playlistName": "Coming Soon",
        "playlistType": "ComingSoon",
        "height": "270",
        "width": "140",
        "playListTypeId": 7,
        "playlistItems": [
            {
                "totalRows": 1,
                "playListId": "239",
                "category": "Movies",
                "mediaID": "346",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Manje Bistre 2",
                "webThumbnail": "https://images.kableone.com/Images/MediaTest/1450250jpg_-1_168e.jpg?im=Resize,width=450",
                "mobileThumbnail": null,
                "fullPageBanner": "https://images.kableone.com/Images/MediaTest/119201080jpg_-3_612f.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/SubedarScene/index4.m3u8",
                "shortDescription": "Manje Bistre 2 is a Punjabi comedy sequel that follows the escapades of a lively Punjabi family during a destination wedding in Canada.",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Comedy, Drama, Romance",
                "releasedYear": "2019",
                "ageRangeId": "U",
                "duration": "2:5:0",
                "rating": 2.5,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Manje_Bistre_2/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            }
        ]
    },
    {
        "playListId": 262,
        "playlistName": "Test Crousel",
        "playlistType": "ComingSoon",
        "height": "270",
        "width": "140",
        "playListTypeId": 7,
        "playlistItems": [
            {
                "totalRows": 6,
                "playListId": "262",
                "category": "Movies",
                "mediaID": "209",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Asees",
                "webThumbnail": "https://images.kableone.com/Images/Media/asees450x250jpg_-1_81e9.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/Media/337x6763jpg_7_8db4.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/asees1920x1080jpg_-3_3604.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Asses/master.m3u8",
                "shortDescription": "\"Asees\" (2018) is a touching Punjabi drama portraying the bond between a mother and her son. The narrative unfolds against the backdrop of partition,",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama",
                "releasedYear": "2018",
                "ageRangeId": "A 18",
                "duration": "2:07:0",
                "rating": 4.4,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Asses/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 6,
                "playListId": "262",
                "category": "Movies",
                "mediaID": "275",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Manje Bistre",
                "webThumbnail": "https://images.kableone.com/Images/Media/Manje_Bistre_450_250_24a8.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/Media/337x6761jpg_7_e6c8.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/Media/Manje_Bistre_1920_1080_db21.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": null,
                "shortDescription": "\"Manje Bistre\" is a Punjabi comedy-drama that revolves around a traditional Punjabi wedding. Filled with humor, it depicts the clash of rural and urban cultures,",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Comedy, Drama",
                "releasedYear": "2017",
                "ageRangeId": "18",
                "duration": "2:17:0",
                "rating": 4,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Manje_Bistre/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 6,
                "playListId": "262",
                "category": "Movies",
                "mediaID": "282",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Snowman",
                "webThumbnail": "https://images.kableone.com/Images/MediaTest/snowman450x250-Copypng-10bb5jpeg_-1_ef75.jpeg?im=Resize,width=450",
                "mobileThumbnail": null,
                "fullPageBanner": "https://images.kableone.com/Images/MediaTest/snowmanpng-3c6a5jpeg_-3_10fa.jpeg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Snowman1/master.m3u8",
                "shortDescription": "\"Mundeyan Ton Bachke Rahin\" is a 2014 Punjabi romantic comedy featuring Roshan Prince, Jassi Gill, and Simran Kaur Mundi. The film revolves around two friends who, to win their love interests,",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Comedy, Romance",
                "releasedYear": "2014",
                "ageRangeId": "UA 7",
                "duration": "1:17:15",
                "rating": 2.6,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Snowman1/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 6,
                "playListId": "262",
                "category": "Movies",
                "mediaID": "292",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Dil Vil Pyaar Vyaar",
                "webThumbnail": "https://images.kableone.com/Images/Media/Dil_Vil_Pyaar_Vyaar_450_250_8e8c.jpg?im=Resize,width=450",
                "mobileThumbnail": null,
                "fullPageBanner": "https://images.kableone.com/Images/Media/Dil_Vil_Pyaar_Vyaar_1920_1080_599a.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Dil_Vil_Pyaar_Vyaar/master.m3u8",
                "shortDescription": "\"Dil Vil Pyaar Vyaar\" is a 2014 Punjabi romantic drama starring Gurdas Maan, Neeru Bajwa, Jassie Gill and Juhi Chawla. The film weaves a tale of love, friendship,",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama, Family",
                "releasedYear": "2023",
                "ageRangeId": "13",
                "duration": "2:25:0",
                "rating": 3.7,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Dil_Vil_Pyaar_Vyaar/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 6,
                "playListId": "262",
                "category": "Movies",
                "mediaID": "336",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Kulche Chole",
                "webThumbnail": "https://images.kableone.com/Images/MediaTest/1450250jpg_-1_7f0c.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/kulche-cholejpg_7_f9c3.jpg",
                "fullPageBanner": "https://images.kableone.com/Images/MediaTest/119201080jpg_-3_6ccb.jpg?im=Resize,width=1920",
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Kulche_Chole/master.m3u8",
                "shortDescription": "just for testing",
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Drama, Romance",
                "releasedYear": "2023",
                "ageRangeId": "16",
                "duration": "0:0:0",
                "rating": 5,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Kulche_Chole/master.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            },
            {
                "totalRows": 6,
                "playListId": "262",
                "category": "Movies",
                "mediaID": "355",
                "webSeriesID": "0",
                "webSeriesName": null,
                "title": "Sucha Soorma Trailer Hindi",
                "webThumbnail": "https://images.kableone.com/Images/MediaTest/Hindijpg_-1_a719.jpg?im=Resize,width=450",
                "mobileThumbnail": "https://images.kableone.com/Images/MediaTest/CHETASINGH500X1002Hindijpg_7_c7e4.jpg",
                "fullPageBanner": null,
                "logo": null,
                "trailerUrl": "https://media.kableone.com/Previews/Trailer/Cheta_Singh_Trailer_Dubbed/master_hi1.m3u8",
                "shortDescription": null,
                "categoryID": "1",
                "playDuration": null,
                "isAddedByUser": false,
                "isLikedByUser": false,
                "genre": "Action",
                "releasedYear": "2024",
                "ageRangeId": "13",
                "duration": "0:0:0",
                "rating": null,
                "preview_url": "https://media.kableone.com/Previews/Trailer/Cheta_Singh_Trailer_Dubbed/master_hi1.m3u8",
                "isMediaPublished": true,
                "openWebSeries": false
            }
        ]
    }
];
function TestComp() {
  return (
    <VerticalList1 data  = {data}/>
  )
}

export default TestComp