const cacheStore = {};

export const SCREEN_KEYS = {
  HOME:{
  HOME_PAGE: 'HOME_PAGE',
  MOVIES_HOME_PAGE : 'MOVIES_HOME_PAGE',
  WEBSERIES_HOME_PAGE: 'WEBSERIES_HOME_PAGE',
  RADIO_HOME_PAGE: 'RADIO_HOME_PAGE',
  LIVE_TV_HOME_PAGE: 'LIVE_TV_HOME_PAGE',
  SEARCH_HOME_PAGE: 'SEARCH_HOME_PAGE',
  FAVORITES_HOME_PAGE: 'FAVOURITES_HOME_PAGE',
  PROFILE_HOME_PAGE: 'PROFILE_HOME_PAGE',
  SEE_ALL_HOME_PAGE: 'SEE_ALL_HOME_PAGE'
  },
  DETAILS:{
     MOVIES_DETAIL_PAGE : 'MOVIES_DETAIL_PAGE',
  WEBSERIES_DETAIL_PAGE: 'WEBSERIES_DETAIL_PAGE',
  RADIO_DETAIL_PAGE: 'RADIO_DETAIL_PAGE',
  LIVE_TV_DETAIL_PAGE: 'LIVE_TV_DETAIL_PAGE',
  },
  PLAYER:{
     MOVIES_PLAYER_PAGE : 'MOVIES_PLAYER_PAGE',
  WEBSERIES_PLAYER_PAGE: 'WEBSERIES_PLAYER_PAGE',
  RADIO_PLAYER_PAGE: 'RADIO_PLAYER_PAGE',
  LIVE_TV_PLAYER_PAGE: 'LIVE_TV_PLAYER_PAGE',
  },
  LOGIN:'LOGIN_PAGE',
  SCREEN_SAVER:'SCREEN_SAVER_PAGE',
  STREAMLIMIT_SCREEN: 'STREAMLIMIT_SCREEN'
}

export const CACHE_KEYS = {
  RADIO: {
    HOME_DATA: "RADIO_HOME_DATA",
    BANNERS_DATA: "RADIO_BANNER_DATA",
  },
  HOME_PAGE: {
    HOME_DATA: "HOME_DATA",
    BANNERS_DATA: "HOME_BANNER_DATA",
  },
  MOVIE_PAGE: {
    HOME_DATA: "MOVIE_HOME_DATA",
    BANNERS_DATA: "MOVIE_BANNER_DATA",
  },
  WEBSERIES_PAGE:{
    HOME_DATA: "WEB_HOME_DATA",
    BANNERS_DATA: "WEB_BANNER_DATA",
  },
  LIVE_TV_PAGE:{
    HOME_DATA: "LIVETV_HOME_DATA",
    BANNERS_DATA: "LIVETV_BANNER_DATA",
  },
  MENU:{
    MENU_DATA: 'MENU_DATA'
  },
  API_KEY:{
    API_KEY_DATA: 'API_KEY_DATA',
    APP_IDLE_TIME: 'APP_IDLE_TIME',
    APP_MIN_VERSION: 'APP_MIN_VERSION'
  },
  FAVOURITES:{
    FAVOURITE_DATA: 'FAVOUORITE_DATA'
  },
  SEARCH:{
    TRENDING_SEARCH: 'TRENDING_SEARCH_DATA'
  },
  SCREENSAVER_CONTENT:{
    SCREENSAVER_DATA: 'SCREENSAVER_DATA'
  },
  CURRENT_SCREEN: 'CURRENT_SCREEN',
  SHOW_NO_INTERNET_MESSAGE: 'SHOW_NO_INTERNET_MESSAGE',
  NO_INTERNET_SERVER_MESSAGE: 'NO_INTERNET_SERVER_MESSAGE',
};

export const setCache = (key, data) => {
  cacheStore[key] = {
    data,
    timestamp: Date.now(),
  };
};

export const getCache = (key) => {
  return cacheStore[key]?.data || null;
};

export const hasCache = (key) => {
  return !!cacheStore[key];
};

export const clearCache = (key) => {
  delete cacheStore[key];
};

export const clearAllCache = () => {
  Object.keys(cacheStore).forEach((key) => delete cacheStore[key]);
};
